// Module
var Constants;
(function (Constants) {
    //Rule Object Types
    Constants.OBJECT_TYPE_QUESTION = 1;
    Constants.OBJECT_TYPE_OUTLINE_NODE = 2;
    Constants.OBJECT_TYPE_OUTLINE_TAB = 3;
    Constants.OBJECT_TYPE_TEMPLATE = 4;
    Constants.OBJECT_TYPE_EXTERNAL_PROCESS = 7;

    //Rule Condition Types
    Constants.CONDITION_EQUAL = 100;
    Constants.CONDITION_NOT_EQUAL = 101;
    Constants.CONDITION_BLANK = 102;
    Constants.CONDITION_NOT_BLANK = 103;
    Constants.CONDITION_EMPTY = 200;
    Constants.CONDITION_NOT_EMPTY = 201;
    Constants.CONDITION_CONTAINS = 202;
    Constants.CONDITION_NOT_CONTAIN = 203;
    Constants.CONDITION_VISIBLE = 300;
    Constants.CONDITION_NOT_VISIBLE = 301;
    Constants.CONDITION_ENABLED = 302;
    Constants.CONDITION_NOT_ENABLED = 303;
    Constants.CONDITION_REQUIRED = 304;
    Constants.CONDITION_NOT_REQUIRED = 305;

    Constants.CONDITION_VALUE_CHANGED = 104;
    Constants.CONDITION_EVENT_FIRED = 307;

    //Rule Actions
    Constants.ACTION_ENABLE_QUESTION = 1;
    Constants.ACTION_DISABLE_QUESTION = 2;
    Constants.ACTION_REQUIRE_QUESTION = 3;
    Constants.ACTION_NOT_REQUIRE_QUESTION = 4;
    Constants.ACTION_ENABLE_REQUIRE_QUESTION = 5;
    Constants.ACTION_DISABLE_AND_NOT_REQUIRE_QUESTION = 6;
    Constants.ACTION_CHANGE_REPONSE_LIST_QUESTION = 7;
    Constants.ACTION_SHOW_QUESTION = 8;
    Constants.ACTION_HIDE_QUESTION = 9;
    Constants.ACTION_CHANGE_PROPERTY_QUESTION = 10;

    Constants.ACTION_ENABLE_ALL_QUESTIONS_ON_NODE = 20;
    Constants.ACTION_DISABLE_ALL_QUESTIONS_ON_NODE = 21;
    Constants.ACTION_REQUIRE_ALL_QUESTIONS_ON_NODE = 22;
    Constants.ACTION_NOT_REQUIRE_ANY_QUESTION_ON_NODE = 23;
    Constants.ACTION_ENABLE_REQUIRE_ALL_QUESTION_ON_NODE = 24;
    Constants.ACTION_DISABLE_ALL_NOT_REQUIRE_ANY_QUESTION_ON_NODE = 25;
    Constants.ACTION_SHOW_ALL_QUESTIONS_ON_NODE = 26;
    Constants.ACTION_HIDE_ALL_QUESTIONS_ON_NODE = 27;
    Constants.ACTION_ENABLE_NODE = 28;
    Constants.ACTION_DISABLE_NODE = 29;
    Constants.ACTION_CHANGE_PROPERTY_FOR_NODE = 30;

    Constants.ACTION_SHOW_TAB = 40;
    Constants.ACTION_HIDE_TAB = 41;
    Constants.ACTION_CHANGE_PROPERTY_FOR_TAB = 42;

    Constants.ACTION_LOAD_TEMPLATE = 60;
    Constants.ACTION_UNLOAD_TEMPLATE = 61;
    Constants.ACTION_UNLOAD_CHILDREN_FOR_TEMPLATE = 62;

    Constants.QUESTION_TYPE_TEXTFIELD = 'TEXTFIELD';
    Constants.QUESTION_TYPE_TEXTMASK = 'TEXTMASK';
    Constants.QUESTION_TYPE_NUMERIC = 'NUMERIC';
    Constants.QUESTION_TYPE_SPINNER = 'SPINNER';
    Constants.QUESTION_TYPE_TEXTAREA = 'TEXTAREA';
    Constants.QUESTION_TYPE_MEMO = 'MEMO';
    Constants.QUESTION_TYPE_LABEL = 'LABEL';
    Constants.QUESTION_TYPE_COMBOBOX = 'COMBOBOX';
    Constants.QUESTION_TYPE_RADIO_GROUP = 'RADIO_GROUP';
    Constants.QUESTION_TYPE_CHECKBOX_GROUP = 'CHECKBOX_GROUP';
    Constants.QUESTION_TYPE_DATE = 'DATE';
    Constants.QUESTION_TYPE_MONTH_YEAR = 'MONTH_YEAR';
    Constants.QUESTION_TYPE_CHECKBOX = 'CHECKBOX';

    Constants.QUESTION_TYPE_HEADER = 'HEADER';
    Constants.QUESTION_TYPE_HTML = 'HTML';
    Constants.QUESTION_TYPE_MESSAGE = 'MESSAGE';
    Constants.QUESTION_TYPE_FILE_MULTI = 'FILE_MULTI';

    Constants.QUESTION_TYPE_ADDRESS = "ADDRESS";
    Constants.QUESTION_TYPE_BUTTON = "BUTTON";
    Constants.QUESTION_TYPE_COLOR = "COLOR";
    Constants.QUESTION_TYPE_CONTACT = "CONTACT";
    Constants.QUESTION_TYPE_CONTACT_ADDRESS = "CONTACT_ADDRESS";
    Constants.QUESTION_TYPE_CONTACT_COMPLEX = "CONTACT_COMPLEX";
    Constants.QUESTION_TYPE_CONTACT_MULTI = "CONTACT_MULTI";
    Constants.QUESTION_TYPE_COUNTRY = "COUNTRY";
    Constants.QUESTION_TYPE_DIVIDER = "DIVIDER";
    Constants.QUESTION_TYPE_ESTABLISHMENT_ADDRESS = "ESTABLISHMENT_ADDRESS";
    Constants.QUESTION_TYPE_ESTABLISHMENT_COMPLEX = "ESTABLISHMENT_COMPLEX";
    Constants.QUESTION_TYPE_ESTABLISHMENT_MULTI = "ESTABLISHMENT_MULTI";
    Constants.QUESTION_TYPE_FILE = "FILE";
    Constants.QUESTION_TYPE_FILE_LOCATION = "FILE_LOCATION";
    Constants.QUESTION_TYPE_FOLDER_LOCATION = "FOLDER_LOCATION";
    Constants.QUESTION_TYPE_FOOTER = "FOOTER";
    Constants.QUESTION_TYPE_GUIDANCE = "GUIDANCE";
    Constants.QUESTION_TYPE_HEADER_STEP = "HEADER_STEP";
    Constants.QUESTION_TYPE_INDENT = "INDENT";
    Constants.QUESTION_TYPE_LIST_ITEM = "LIST_ITEM";
    Constants.QUESTION_TYPE_MDR_CODE_LIST = "MDR_CODE_LIST";
    Constants.QUESTION_TYPE_MDR_MANUFACTURER_CODE = "MDR_MANUFACTURER_CODE";
    Constants.QUESTION_TYPE_MDR_USER_FACILITY_CODE = "MDR_USER_FACILITY_CODE";
    Constants.QUESTION_TYPE_MODEL = "MODEL";
    Constants.QUESTION_TYPE_OPTION_LIST = "OPTION_LIST";
    Constants.QUESTION_TYPE_OPTION_LIST_EXTENDED = "OPTION_LIST_EXTENDED";
    Constants.QUESTION_TYPE_PARENT_XML_ID = "PARENT_XML_ID";
    Constants.QUESTION_TYPE_PASSWORD = "PASSWORD";
    Constants.QUESTION_TYPE_PHONE = "PHONE";
    Constants.QUESTION_TYPE_PRODUCT_CODE = "PRODUCT_CODE";
    Constants.QUESTION_TYPE_PRODUCT_CODE_MULTI = "PRODUCT_CODE_MULTI";
    Constants.QUESTION_TYPE_PRODUCT_CODE_RH = "PRODUCT_CODE_RH";
    Constants.QUESTION_TYPE_PRODUCT_CODE_MULTI_RH = "PRODUCT_CODE_MULTI_RH";
    Constants.QUESTION_TYPE_REFERENCE_NUMBERS = "REFERENCE_NUMBERS";
    Constants.QUESTION_TYPE_RPS = "RPS";
    Constants.QUESTION_TYPE_STANDARDS = "STANDARDS";
    Constants.QUESTION_TYPE_STATE = "STATE";
    Constants.QUESTION_TYPE_TABLE = "TABLE";
    Constants.QUESTION_TYPE_TEXT = "TEXT";
    Constants.QUESTION_TYPE_UNDER_CONSTRUCTION = "UNDER_CONSTRUCTION";
    Constants.QUESTION_TYPE_ZIP = "ZIP";

    Constants.QUESTION_TYPE_IMAGE = 'IMAGE';
    Constants.QUESTION_TYPE_CAMERA = 'CAMERA';
    Constants.QUESTION_TYPE_VIDEO = 'VIDEO';
    Constants.QUESTION_TYPE_SOUND = 'SOUND';
    Constants.QUESTION_TYPE_VOICE_RECORDER = 'VOICE_RECORDER';
    Constants.QUESTION_TYPE_CAMCORDER = 'CAMCORDER';
})(Constants || (Constants = {}));
//# sourceMappingURL=Constants.js.map
